# Generated by Django 5.2 on 2025-04-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeupload',
            name='file',
            field=models.FileField(upload_to='resumes/files'),
        ),
    ]
